services:
  db:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD : ${DB_PASSWORD}
      MYSQL_DATABASE : ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - board_network
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  web:
    build: .
    container_name: board_web
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    networks:
      - board_network
    command:
      [
        "sh",
        "-c",
        "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn mysite.wsgi:application 
        --bind 0.0.0.0:8000 --workers 2"
      ]

  nginx :
    image: nginx:latest
    container_name: board_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - board_network

volumes:
  db_data:
  static_volume:
  media_volume:

networks:
  board_network:
    driver: bridge