# -*- coding: utf-8 -*-
"""straberrey_machine_learing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P45zHG2mTSTWAox3EF2PDDqwEKrt893U
"""

# ====================== 0. 라이브러리 설치 ======================
!pip install transparent-background tqdm pandas

import zipfile
import os
from pathlib import Path
import json
import pandas as pd
from tqdm import tqdm
from transparent_background import Remover
from PIL import Image
import shutil

# ====================== 1. 설정 (당신이 바꿀 부분) ======================
INPUT_ZIP = "Sample.zip"                    # ← 당신의 원본 zip 파일명
OUTPUT_ZIP = "processed_sample.zip"         # ← 최종 결과 zip (이미지 + JSON 같이 들어있음)
TEMP_DIR = Path("temp_extracted")           # 임시 압축해제 폴더
PROCESSED_DIR = Path("processed_images")    # 배경 제거된 이미지 저장 폴더 (파트 구조 유지)

TEMP_DIR.mkdir(exist_ok=True)
PROCESSED_DIR.mkdir(exist_ok=True)

remover = Remover()

print("🚀 단계 1: sample.zip 압축 해제 중...")
with zipfile.ZipFile(INPUT_ZIP, 'r') as zf:
    zf.extractall(TEMP_DIR)
print(f"✅ 압축 해제 완료! (총 {len(list(TEMP_DIR.rglob('*')))}개 항목)")

# ====================== 2. 라벨 JSON 자동 찾기 + 분석 ======================
print("\n🚀 단계 2: 라벨 JSON 찾기 및 분석 중...")

label_data = {}
image_extensions = ('.jpg', '.jpeg', '.png', '.webp')

# 원천 데이터와 라벨링 데이터의 기본 경로 설정 (데이터셋 구조에 맞게)
BASE_DATA_DIR = TEMP_DIR / "Sample"
ORIGINAL_IMAGE_ROOT = BASE_DATA_DIR / "01.원천데이터"
LABEL_JSON_ROOT = BASE_DATA_DIR / "02.라벨링데이터"

if ORIGINAL_IMAGE_ROOT.exists() and LABEL_JSON_ROOT.exists():
    for img_path in tqdm(list(ORIGINAL_IMAGE_ROOT.rglob('*')), desc="라벨 파일 매칭"):
        if img_path.is_file() and img_path.name.lower().endswith(image_extensions):
            # 이미지 경로를 기반으로 라벨 JSON 경로 추론
            relative_img_path = img_path.relative_to(ORIGINAL_IMAGE_ROOT)
            json_path = LABEL_JSON_ROOT / relative_img_path.with_suffix('.json')

            if json_path.exists():
                try:
                    with open(json_path, 'r', encoding='utf-8') as f:
                        json_content = json.load(f)
                        # JSON 구조에 따라 라벨 추출. 'disease_class' 필드를 가정
                        # 데이터셋 JSON 구조에 따라 이 부분을 수정해야 합니다.
                        # 예: json_content.get('label') 또는 json_content['annotation']['image']['disease_state']
                        label = json_content.get('images', {}).get('disease_class') # <-- 수정된 부분
                        if label:
                            # 원본 zip 내에서의 상대 경로를 키로 사용
                            # 예: "Sample/01.원천데이터/01.딸기/001.설향/01.정상/딸기_설향_정상_13_001_220930101738.jpg"
                            original_full_path_str = str(Path("Sample") / "01.원천데이터" / relative_img_path)
                            label_data[original_full_path_str] = label
                        # else:
                            # print(f"⚠️ {json_path} 에서 라벨(disease_state)을 찾을 수 없습니다.")
                except Exception as e:
                    print(f"❌ {json_path} 파싱 오류: {e}")
            # else:
            #     print(f"⚠️ {json_path} 에 해당하는 라벨 JSON 파일을 찾을 수 없습니다.")

    if label_data:
        df_label = pd.DataFrame(list(label_data.items()), columns=['original_filename', 'label'])
        print(f"📊 JSON 분석 완료 → 총 {len(df_label)}개 이미지 라벨")
        print("클래스 분포:\n", df_label['label'].value_counts())
    else:
        print("⚠️ JSON 라벨 파일을 찾지 못했습니다. 수동으로 업로드하거나 알려주세요.")
else:
    print("⚠️ 원천 데이터 또는 라벨링 데이터 경로를 찾을 수 없습니다. 데이터셋 구조를 확인해주세요.")

# ====================== 3. 각 파트(하위 폴더)별 배경 제거 ======================
print("\n🚀 단계 3: 파트별 이미지 배경 제거 중... (원본 폴더 구조 유지)")

# image_extensions는 이미 위에서 정의됨
processed_count = 0
mapping = {}   # 원본 → 새 파일명 매핑 (나중에 JSON 업데이트용)

for root, dirs, files in os.walk(TEMP_DIR):
    for file in files:
        if file.lower().endswith(image_extensions):
            img_path = Path(root) / file

            # TEMP_DIR에 대한 상대 경로를 가져와서 나중에 매핑에 사용
            rel_path_in_temp = img_path.relative_to(TEMP_DIR)

            # 파트 구조 유지하면서 저장 경로 생성
            # 원래 파일명에서 'Sample/' 부분을 제거하고 시작 (processed_images 내부에 Sample이 또 생기는 것을 방지)
            new_name_parts = list(rel_path_in_temp.parts)
            if new_name_parts and new_name_parts[0] == "Sample":
                new_name_parts = new_name_parts[1:]

            # 안전한 파일명으로 변환: 슬래시를 이중 언더바로 대체하고 PNG 확장자로 변경
            safe_file_name = Path('_'.join(new_name_parts)).with_suffix('.png').name
            save_path = PROCESSED_DIR / safe_file_name

            try:
                img = Image.open(img_path).convert("RGB")
                result = remover.process(img)
                result.save(save_path, "PNG")

                # 매핑 저장 (JSON 업데이트용)
                # 원본 경로를 키로, 새로 저장된 파일명을 값으로
                mapping[str(rel_path_in_temp)] = str(save_path.name)

                processed_count += 1
                if processed_count % 50 == 0:
                    print(f"   처리 중... {processed_count}장 완료")

            except Exception as e:
                print(f"❌ 실패: {img_path} → {e}")

print(f"✅ 배경 제거 완료! 총 {processed_count}장 처리")

# ====================== 4. JSON 업데이트 + 매핑 파일 생성 ======================
if label_data: # 라벨 데이터가 성공적으로 로드된 경우에만 진행
    updated_labels = {}
    for orig_full_path, label in label_data.items():
        # 원본 zip 내부의 상대 경로 (예: 'Sample/01.원천데이터/...')를
        # 매핑 딕셔너리의 키와 비교하기 위해 Path 객체로 변환
        orig_path_in_temp = Path(orig_full_path)

        # 매핑 딕셔너리에 저장된 키는 TEMP_DIR에 대한 상대 경로
        # 이전에 매핑을 저장할 때 str(rel_path)로 저장했으므로,
        # 여기서는 str(orig_path_in_temp)와 비교할 수 있도록 맞춰줘야 함.
        # 따라서 orig_full_path 그 자체를 키로 사용하면 됨.
        converted_name = mapping.get(orig_full_path, None)

        if converted_name:
            updated_labels[converted_name] = label
        # else:
            # print(f"⚠️ 매핑을 찾을 수 없는 원본 파일: {orig_full_path}")

    if updated_labels:
        with open(PROCESSED_DIR / "labels.json", 'w', encoding='utf-8') as f:
            json.dump(updated_labels, f, ensure_ascii=False, indent=2)

        # 추가로 pandas 매핑 파일도 저장 (학습 때 편함)
        pd.DataFrame(list(updated_labels.items()), columns=['image', 'label']).to_csv(
            PROCESSED_DIR / "label_mapping.csv", index=False, encoding='utf-8-sig')

        print("✅ labels.json + label_mapping.csv 업데이트 완료")
    else:
        print("⚠️ 업데이트할 라벨 데이터가 없습니다.")
else:
    print("⚠️ 라벨 데이터가 없으므로 labels.json 및 label_mapping.csv를 생성하지 않습니다.")

# ====================== 5. 배경제거 이미지 + JSON을 하나의 zip으로 압축 ======================
print("\n🚀 단계 5: 최종 zip 생성 중... (이미지 + JSON 같이!)")

with zipfile.ZipFile(OUTPUT_ZIP, 'w', zipfile.ZIP_DEFLATED) as zipf:
    # processed_images 폴더 전체 추가 (파트 구조 그대로)
    for root, dirs, files in os.walk(PROCESSED_DIR):
        for file in files:
            file_path = Path(root) / file
            # zip 파일 내부에 'processed_images/' 경로가 포함되도록 arcname 설정
            arcname = Path("processed_images") / file_path.name
            zipf.write(file_path, arcname)

    # JSON도 함께 (루트에)
    if (PROCESSED_DIR / "labels.json").exists():
        zipf.write(PROCESSED_DIR / "labels.json", "labels.json")
    if (PROCESSED_DIR / "label_mapping.csv").exists():
        zipf.write(PROCESSED_DIR / "label_mapping.csv", "label_mapping.csv")

print(f"🎉 완성! → {OUTPUT_ZIP} 생성됨")
print("   내용물: processed_images/ (배경제거 PNG들) + labels.json")

# ====================== 6. Colab에서 바로 다운로드 ======================
from google.colab import files
files.download(OUTPUT_ZIP)

"""# 배경 제거한 이미지들을 압축한 zip을 가지고 풀고 난 다음 학습 준비 ~ Grad-CAM까지 시행"""

# ────────────────────────────────────────────────
#          [배경 제거 완료 zip → 학습 준비 ~ Grad-CAM]
# ────────────────────────────────────────────────

# 1. 기본 설치 & 임포트
!pip install -q torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install -q grad-cam seaborn scikit-learn pandas tqdm

import os
import zipfile
import json
from pathlib import Path
import pandas as pd
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from tqdm.auto import tqdm

# pytorch-grad-cam
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget
from pytorch_grad_cam.utils.image import show_cam_on_image

# ────────────────────────────────────────────────
#  1. zip 파일 해제 & 경로 설정
# ────────────────────────────────────────────────

ZIP_PATH = "processed_sample.zip"           # ← 당신이 만든 zip 파일명으로 변경
EXTRACT_ROOT = Path("extracted_processed")

if not EXTRACT_ROOT.exists():
    with zipfile.ZipFile(ZIP_PATH, 'r') as zf:
        zf.extractall(EXTRACT_ROOT)
    print("zip 압축 해제 완료")

# 가장 일반적인 구조 두 가지 지원
IMG_DIR = EXTRACT_ROOT / "processed_images"
if not IMG_DIR.exists():
    IMG_DIR = EXTRACT_ROOT  # 바로 이미지들이 루트에 있는 경우도 있음

LABEL_JSON = next(IMG_DIR.rglob("labels.json"), None)
LABEL_CSV  = next(IMG_DIR.rglob("label_mapping.csv"), None)

print("이미지 폴더:", IMG_DIR)
print("라벨 파일:", LABEL_JSON or LABEL_CSV)

# ────────────────────────────────────────────────
#  2. 라벨 데이터 로드 & EDA (pandas 적극 활용)
# ────────────────────────────────────────────────

if LABEL_JSON:
    with open(LABEL_JSON, encoding="utf-8") as f:
        label_dict = json.load(f)
    df = pd.DataFrame(label_dict.items(), columns=["filename", "label"])
elif LABEL_CSV:
    df = pd.read_csv(LABEL_CSV)
    df = df.rename(columns={"image":"filename"})
else:
    raise FileNotFoundError("labels.json 또는 label_mapping.csv 파일을 찾을 수 없습니다.")

# 파일 경로 완성
df["fullpath"] = df["filename"].apply(lambda x: IMG_DIR / x)
df = df[df["fullpath"].apply(lambda p: p.exists())].reset_index(drop=True)

print(f"유효한 이미지-라벨 쌍 개수 : {len(df):,}장")

# 기본 통계
print("\n클래스 분포")
display(df["label"].value_counts().to_frame("count"))

print("\n클래스 비율")
display((df["label"].value_counts(normalize=True)*100).round(2).to_frame("%"))

# 라벨 인코딩
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["label_idx"] = le.fit_transform(df["label"])
NUM_CLASSES = len(le.classes_)
print(f"\n클래스 수 : {NUM_CLASSES}")
print("클래스 이름 :", le.classes_)

# ────────────────────────────────────────────────
#  3. train / valid split
# ────────────────────────────────────────────────

train_df, valid_df = train_test_split(
    df,
    test_size=0.20,
    stratify=df["label_idx"],
    random_state=42
)

print(f"train: {len(train_df):4d}장   valid: {len(valid_df):4d}장")

# ────────────────────────────────────────────────
#  4. 데이터 증강 파이프라인 (torchvision)
# ────────────────────────────────────────────────

train_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.RandomResizedCrop(224, scale=(0.75,1.0)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(degrees=15),
    transforms.ColorJitter(brightness=0.15, contrast=0.15, saturation=0.15),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std =[0.229, 0.224, 0.225])
])

valid_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std =[0.229, 0.224, 0.225])
])


class TransparentBG_Dataset(Dataset):
    def __init__(self, dataframe, transform=None):
        self.df = dataframe.reset_index(drop=True)
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img = Image.open(row["fullpath"]).convert("RGB")

        if self.transform:
            img = self.transform(img)

        label = row["label_idx"]
        return img, label


train_ds = TransparentBG_Dataset(train_df, train_transform)
valid_ds = TransparentBG_Dataset(valid_df, valid_transform)

train_loader = DataLoader(train_ds, batch_size=32, shuffle=True,  num_workers=0, pin_memory=True)
valid_loader = DataLoader(valid_ds, batch_size=48, shuffle=False, num_workers=0, pin_memory=True)

# ────────────────────────────────────────────────
#  5. 모델 정의 & 전이학습 설정
# ────────────────────────────────────────────────

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("사용 장치:", device)

model = models.resnet50(weights="IMAGENET1K_V2")
# model = models.efficientnet_b0(weights="IMAGENET1K_V1")   # ← 더 가벼운 모델 원하면 변경

# 마지막 레이어 교체
in_features = model.fc.in_features
model.fc = nn.Linear(in_features, NUM_CLASSES)

model = model.to(device)

criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4, weight_decay=1e-2)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=15)

# 처음 10 에포크는 fc만 학습하는 전략도 가능
# for param in model.parameters():
#     param.requires_grad = False
# for param in model.fc.parameters():
#     param.requires_grad = True

# ────────────────────────────────────────────────
#  6. 학습 루프
# ────────────────────────────────────────────────

def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()
    total_loss = 0
    correct = 0
    total = 0

    for images, labels in tqdm(loader, desc="train"):
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * images.size(0)
        correct += (outputs.argmax(dim=1) == labels).sum().item()
        total += labels.size(0)

    return total_loss / total, correct / total


def validate(model, loader, criterion, device):
    model.eval()
    total_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in tqdm(loader, desc="valid"):
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            loss = criterion(outputs, labels)

            total_loss += loss.item() * images.size(0)
            correct += (outputs.argmax(dim=1) == labels).sum().item()
            total += labels.size(0)

    return total_loss / total, correct / total


history = {"train_loss":[], "train_acc":[], "val_loss":[], "val_acc":[]}

best_acc = 0
best_epoch = 0

for epoch in range(18):

    tr_loss, tr_acc = train_one_epoch(model, train_loader, optimizer, criterion, device)
    va_loss, va_acc = validate(model, valid_loader, criterion, device)

    history["train_loss"].append(tr_loss)
    history["train_acc"].append(tr_acc)
    history["val_loss"].append(va_loss)
    history["val_acc"].append(va_acc)

    print(f"Epoch {epoch+1:2d}   train loss {tr_loss:.4f}  acc {tr_acc:.4f}    val loss {va_loss:.4f}  acc {va_acc:.4f}")

    scheduler.step()

    if va_acc > best_acc:
        best_acc = va_acc
        best_epoch = epoch+1
        torch.save(model.state_dict(), "best_model.pt")
        print(f"   ← best model saved (acc: {va_acc:.4f})")

print(f"\n최고 성능 : epoch {best_epoch} , val acc {best_acc:.4f}")

# ────────────────────────────────────────────────
#  7. 학습 곡선 시각화
# ────────────────────────────────────────────────

fig, (ax1, ax2) = plt.subplots(1,2, figsize=(14,5))

ax1.plot(history["train_loss"], label="train loss")
ax1.plot(history["val_loss"],   label="val loss")
ax1.set_title("Loss")
ax1.legend(); ax1.grid(True, alpha=0.3)

ax2.plot(history["train_acc"], label="train acc")
ax2.plot(history["val_acc"],   label="val acc")
ax2.set_title("Accuracy")
ax2.legend(); ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# ────────────────────────────────────────────────
#  8. Confusion Matrix & Classification Report
# ────────────────────────────────────────────────

@torch.no_grad()
def get_all_preds_labels(model, loader, device):
    model.eval()
    preds, trues = [], []
    for images, labels in tqdm(loader, desc="inference"):
        images = images.to(device)
        outputs = model(images)
        preds.append(outputs.argmax(dim=1).cpu())
        trues.append(labels)
    return torch.cat(preds).numpy(), torch.cat(trues).numpy()

y_pred, y_true = get_all_preds_labels(model, valid_loader, device)

cm = confusion_matrix(y_true, y_pred)
labels = le.classes_

plt.figure(figsize=(9,8))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=labels, yticklabels=labels,
            cbar=False)
plt.title("Confusion Matrix (Validation set)")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

print("\nClassification Report\n")
print(classification_report(y_true, y_pred, target_names=labels, digits=3))

# ────────────────────────────────────────────────
#  9. Grad-CAM 시각화 (마지막 5개 샘플 예시)
# ────────────────────────────────────────────────

import cv2 # Import OpenCV for resizing

target_layers = [model.layer4[-1]]   # ResNet50 기준
cam = GradCAM(model=model, target_layers=target_layers)

sample_rows = valid_df.sample(5, random_state=42).reset_index(drop=True)

fig, axes = plt.subplots(1,5, figsize=(18,4))

for i, row in enumerate(sample_rows.itertuples()):
    img_path = row.fullpath
    true_label = row.label
    true_idx  = row.label_idx

    img_pil = Image.open(img_path).convert("RGB")
    img_tensor = valid_transform(img_pil).unsqueeze(0).to(device)

    targets = [ClassifierOutputTarget(true_idx)]
    grayscale_cam = cam(input_tensor=img_tensor, targets=targets)[0, :]

    img_np = np.array(img_pil) / 255.0
    # Resize grayscale_cam to match img_np's spatial dimensions
    # cv2.resize expects (width, height)
    grayscale_cam_resized = cv2.resize(grayscale_cam, (img_pil.width, img_pil.height))

    visualization = show_cam_on_image(img_np, grayscale_cam_resized, use_rgb=True)

    axes[i].imshow(visualization)
    axes[i].set_title(f"True: {true_label}", fontsize=10)
    axes[i].axis("off")

plt.suptitle("Grad-CAM visualization (warmer color = more important region)", y=1.02)
plt.tight_layout()
plt.show()

print("""
Grad-CAM 해석 가이드
────────────────────
• 빨간색 영역 = 모델이 가장 강하게 주목한 부분
• 배경이 제거되어 있으므로 대부분 객체 자체에 집중해야 정상
• 빨간색이 객체의 특징적인 부분(머리, 발, 로고, 손잡이 등)에 잘 맞춰져 있다면 모델이 올바른 판단 근거를 학습한 것
• 배경이나 무의미한 영역에 빨간색이 강하게 나타난다면 → 데이터 증강 강화 / 정규화 강화 / 더 많은 에폭 필요
""")