# Generated by Django 6.0.3 on 2026-03-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
    ]
