# Generated by Django 6.0.3 on 2026-03-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_post_view_count_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='postview',
            name='ip_adderss',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
