# Generated by Django 6.0.3 on 2026-03-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_postview_ip_adderss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postview',
            old_name='ip_adderss',
            new_name='ip_address',
        ),
    ]
